# Generated by Django 4.0 on 2021-12-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descriptio',
            new_name='description',
        ),
    ]
